### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by besarthoxhaj** [besarthoxhaj/dotfiles#2]
- [ ] iTerm settings
- [ ] save `~/.bash_profile`
- [ ] mac settings (like keystroke speed)
- [ ] apps to download like (node, brew, android, xCode, spectalce, iTerm)
- [ ] generate SSH keys and upload it for different services (?)
- [ ] iTerm2
  - `0x15` to `⌘` + `←Delete`
  - `Preferences` > `Profiles` > `Working Directory` tick `Reuse previous session's directory`
- [ ] create `~/.gitconfig` https://git-scm.com/book/en/v2/Git-Basics-Git-Aliases
- [ ] vsCode
  - install git blame, run with `Ctrl+Shift+X` or `⇧⌘X`
